export {StaffModel} from './staff.model'
export {ProblemModel} from './problem-question.model'
export {ExamModel} from './exam.model'
export {KnownFaceDataModel} from './known-face-model.model'
export {FaceDataModel} from './face-hanet.model'
export {CertificateModel} from './certificate.model'
export {BetaTestModel} from './test.model'
export {CenterOnlineDataModel} from './center-online-sync.model'
export { PeopleModel } from './people.model'
export { TagPeopleModel } from './tagpeople.model'
export { FaceImageModel, OldFaceImageModel } from './faceimage.model'
export { STOverrideRoomModel } from './today-schedule.model'
export { ClassLogModel } from './class-log.model'
export { ClientFeedbackModel } from './client-feedback'
export { PointClientTransactionModel } from './point-client.model'
export { ClassInfoModel } from './class-info.model'
